### ISSUE TITLE
are you triggered by this if statement :)

### ISSUE THREAD

**Issue by NickWang11235** [NickWang11235/JavaMayhem#2]
if((y != game.height-playerHeight && game.getGameState().getMap().getArrayMap()[(int)(Math.floor(Math.min(Math.max(y+playerHeight,0),game.height-1)))][(int)Math.floor(x)] == 0) || (y != game.height-playerHeight && game.getGameState().getMap().getArrayMap()[(int)Math.floor(Math.min(Math.max(y+playerHeight,0),game.height-1))][(int)Math.ceil(x+playerWidth)] == 0))

**Comment by derickboss1** [comment]
```ohhhh boy```
